Document: pi-blaster
Title: Debian pi-blaster Manual
Author: <insert document author here>
Abstract: This manual describes what pi-blaster is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pi-blaster/pi-blaster.sgml.gz

Format: postscript
Files: /usr/share/doc/pi-blaster/pi-blaster.ps.gz

Format: text
Files: /usr/share/doc/pi-blaster/pi-blaster.text.gz

Format: HTML
Index: /usr/share/doc/pi-blaster/html/index.html
Files: /usr/share/doc/pi-blaster/html/*.html
