#!/bin/sh
### BEGIN INIT INFO
# Provides:          servoblaster
# Required-Start:
# Required-Stop:
# Should-Start:
# Default-Start:
# Default-Stop:
# Short-Description: Start/Stop the servoblaster kernel driver
# Description:       A kernel driver that lets you control 8 (or more)
#                    servos from your RaspberryPi. Details from here:
#                       www.raspberrypi.org/phpBB3/viewtopic.php?f=37&t=15011
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin

do_start () {
	insmod /lib/modules/$(uname -r)/kernel/drivers/misc/servoblaster/servoblaster.ko
}

do_stop () {
	rmmod servoblaster.ko
}

do_status () {
	return 0
}

case "$1" in
  start|"")
	do_start
	;;
  restart|reload|force-reload)
	do_stop
	do_start
	exit 3
	;;
  stop)
	do_stop
	;;
  status)
	echo "Error: argument '$1' not supported" >&2
	exit $?
	;;
  *)
	echo "Usage: servoblaster [start|stop|restart|reload|force-reload]" >&2
	exit 3
	;;
esac

:
